plugins {
    id 'idea'
    id 'org.springframework.boot' version '3.5.13' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
}

group = 'ru.seleznev'
version = '1.0-SNAPSHOT'

allprojects {
    repositories {
        mavenCentral()
    }
}


subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    group = 'ru.seleznev'
    version = '1.0-SNAPSHOT'

    dependencyManagement {
        imports {
            mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
        }
    }

}
